[build]
    command = "./build.sh"
    functions = "functions"
    publish = "views"

[build.environment]
    GO_IMPORT_PATH = "github/SVincentTran/crypto_watch_test"
    GO111MODULE = "on"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/cryptowatch"
    status = 200